// this file is autogenerated
var UserBaseService = require("./UserBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = UserBaseService.definition.name;


function UserServiceAuth() {
}

UserServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.create(query, next) : next(err);
    });
};

UserServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.update(data, next) : next(err);
    });
};

UserServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.remove(pkValue, next) : next(err);
    });
};

UserServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.findById(pkValue, next) : next(err);
    });
};

UserServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.deleteById(pkValue, next) : next(err);
    });
};

UserServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? UserBaseService.updateById(pkValue, data, next) : next(err);
    });
};

UserServiceAuth.find = function findAuth(query, roles, next) {
    UserBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
UserServiceAuth.count = function countAuth(where, roles, next) {
    UserBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

UserServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
UserServiceAuth.getById = function getByIdAuth(id, roles, next) {
    this.find({"where":{"id":id}}, roles, next); //autogenerated from js configs
};


UserServiceAuth.getByIdAndVersion = function getByIdAndVersionAuth(id,version, roles, next) {
    this.find({"where":{"id":id,"version":version}}, roles, next); //autogenerated from js configs
};




module.exports = UserServiceAuth;