// this file is autogenerated
var ThreadBaseService = require("./ThreadBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = ThreadBaseService.definition.name;


function ThreadServiceAuth() {
}

ThreadServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.create(query, next) : next(err);
    });
};

ThreadServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.update(data, next) : next(err);
    });
};

ThreadServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.remove(pkValue, next) : next(err);
    });
};

ThreadServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.findById(pkValue, next) : next(err);
    });
};

ThreadServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.deleteById(pkValue, next) : next(err);
    });
};

ThreadServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ThreadBaseService.updateById(pkValue, data, next) : next(err);
    });
};

ThreadServiceAuth.find = function findAuth(query, roles, next) {
    ThreadBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
ThreadServiceAuth.count = function countAuth(where, roles, next) {
    ThreadBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

ThreadServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
ThreadServiceAuth.getByLinkedModelIdAndLinkedModelName = function getByLinkedModelIdAndLinkedModelNameAuth(linkedModelId,linkedModelName, roles, next) {
    this.findOne({"where":{"linkedModelId":linkedModelId,"linkedModelName":linkedModelName}}, roles, next); //autogenerated from js configs
};




module.exports = ThreadServiceAuth;