// this file is autogenerated
var PageBaseService = require("./PageBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = PageBaseService.definition.name;


function PageServiceAuth() {
}

PageServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.create(query, next) : next(err);
    });
};

PageServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.update(data, next) : next(err);
    });
};

PageServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.remove(pkValue, next) : next(err);
    });
};

PageServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.findById(pkValue, next) : next(err);
    });
};

PageServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.deleteById(pkValue, next) : next(err);
    });
};

PageServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PageBaseService.updateById(pkValue, data, next) : next(err);
    });
};

PageServiceAuth.find = function findAuth(query, roles, next) {
    PageBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
PageServiceAuth.count = function countAuth(where, roles, next) {
    PageBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

PageServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
PageServiceAuth.getByFriendlyURL = function getByFriendlyURLAuth(friendlyURL, roles, next) {
    this.findOne({"where":{"friendlyURL":friendlyURL}}, roles, next); //autogenerated from js configs
};


PageServiceAuth.getByLayoutId = function getByLayoutIdAuth(layoutId, roles, next) {
    this.find({"where":{"layoutId":layoutId}}, roles, next); //autogenerated from js configs
};


PageServiceAuth.getByThemeId = function getByThemeIdAuth(themeId, roles, next) {
    this.find({"where":{"themeId":themeId}}, roles, next); //autogenerated from js configs
};




module.exports = PageServiceAuth;