// this file is autogenerated
var PageBaseService = require("./PageBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions,
    AuthDAOExtras = require(utils.getLibPath() + "/ServicesHelper/AuthDAOExtras");

var modelName = PageBaseService.definition.name;


function PageServiceAuth() {
}
PageServiceAuth.baseService = PageBaseService;
AuthDAOExtras(PageServiceAuth);


//finders implementation
PageServiceAuth.getByFriendlyURL = function getByFriendlyURLAuth(friendlyURL, roles, next) {
    this.findOne({"where":{"friendlyURL":friendlyURL}}, roles, next); //autogenerated from js configs
};


PageServiceAuth.getByLayoutId = function getByLayoutIdAuth(layoutId, roles, next) {
    this.find({"where":{"layoutId":layoutId}}, roles, next); //autogenerated from js configs
};


PageServiceAuth.getByThemeId = function getByThemeIdAuth(themeId, roles, next) {
    this.find({"where":{"themeId":themeId}}, roles, next); //autogenerated from js configs
};




module.exports = PageServiceAuth;