// this file is autogenerated
var SchemaPermissionsBaseService = require("./SchemaPermissionsBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = SchemaPermissionsBaseService.definition.name;


function SchemaPermissionsServiceAuth() {
}

SchemaPermissionsServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.create(query, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.update(data, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.remove(pkValue, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.findById(pkValue, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.deleteById(pkValue, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? SchemaPermissionsBaseService.updateById(pkValue, data, next) : next(err);
    });
};

SchemaPermissionsServiceAuth.find = function findAuth(query, roles, next) {
    SchemaPermissionsBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
SchemaPermissionsServiceAuth.count = function countAuth(where, roles, next) {
    SchemaPermissionsBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

SchemaPermissionsServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
SchemaPermissionsServiceAuth.getByPermissionSchemaKey = function getByPermissionSchemaKeyAuth(permissionSchemaKey, roles, next) {
    this.findOne({"where":{"permissionSchemaKey":permissionSchemaKey}}, roles, next); //autogenerated from js configs
};




module.exports = SchemaPermissionsServiceAuth;