// this file is autogenerated
var ResourceBaseService = require("./ResourceBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions,
    AuthDAOExtras = require(utils.getLibPath() + "/ServicesHelper/AuthDAOExtras");

var modelName = ResourceBaseService.definition.name;


function ResourceServiceAuth() {
}
ResourceServiceAuth.baseService = ResourceBaseService;
AuthDAOExtras(ResourceServiceAuth);


//finders implementation
ResourceServiceAuth.getByNameAndFolderId = function getByNameAndFolderIdAuth(name,folderId, roles, next) {
    this.find({"where":{"name":name,"folderId":folderId}}, roles, next); //autogenerated from js configs
};


ResourceServiceAuth.getByFolderId = function getByFolderIdAuth(folderId, roles, next) {
    this.find({"where":{"folderId":"folderId"}}, roles, next); //autogenerated from js configs
};




module.exports = ResourceServiceAuth;