// this file is autogenerated
var PluginInstanceBaseService = require("./PluginInstanceBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = PluginInstanceBaseService.definition.name;


function PluginInstanceServiceAuth() {
}

PluginInstanceServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.create(query, next) : next(err);
    });
};

PluginInstanceServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.update(data, next) : next(err);
    });
};

PluginInstanceServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.remove(pkValue, next) : next(err);
    });
};

PluginInstanceServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.findById(pkValue, next) : next(err);
    });
};

PluginInstanceServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.deleteById(pkValue, next) : next(err);
    });
};

PluginInstanceServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? PluginInstanceBaseService.updateById(pkValue, data, next) : next(err);
    });
};

PluginInstanceServiceAuth.find = function findAuth(query, roles, next) {
    PluginInstanceBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
PluginInstanceServiceAuth.count = function countAuth(where, roles, next) {
    PluginInstanceBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

PluginInstanceServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
PluginInstanceServiceAuth.getByPluginNamespaceAndPageId = function getByPluginNamespaceAndPageIdAuth(pluginNamespace,pageId, roles, next) {
    this.find({"where":{"pluginNamespace":pluginNamespace,"pageId":pageId}}, roles, next); //autogenerated from js configs
};




module.exports = PluginInstanceServiceAuth;