// this file is autogenerated
var ArticleBaseService = require("./ArticleBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = ArticleBaseService.definition.name;


function ArticleServiceAuth() {
}

ArticleServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.create(query, next) : next(err);
    });
};

ArticleServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.update(data, next) : next(err);
    });
};

ArticleServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.remove(pkValue, next) : next(err);
    });
};

ArticleServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.findById(pkValue, next) : next(err);
    });
};

ArticleServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.deleteById(pkValue, next) : next(err);
    });
};

ArticleServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleBaseService.updateById(pkValue, data, next) : next(err);
    });
};

ArticleServiceAuth.find = function findAuth(query, roles, next) {
    ArticleBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
ArticleServiceAuth.count = function countAuth(where, roles, next) {
    ArticleBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

ArticleServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation
ArticleServiceAuth.getById = function getByIdAuth(id, roles, next) {
    this.find({"where":{"id":id}}, roles, next); //autogenerated from js configs
};


ArticleServiceAuth.getByIdAndVersion = function getByIdAndVersionAuth(id,version, roles, next) {
    this.find({"where":{"id":id,"version":version}}, roles, next); //autogenerated from js configs
};




module.exports = ArticleServiceAuth;