// this file is autogenerated
var ArticleVersionBaseService = require("./ArticleVersionBaseService"),
    PermissionActions = require(utils.getLibPath() + "/permissions").PermissionActions;

var modelName = ArticleVersionBaseService.definition.name;


function ArticleVersionServiceAuth() {
}

ArticleVersionServiceAuth.create = function createAuth(data, pv, next) {
    pv.hasPermissionWithoutModelId(PermissionActions.ADD, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.create(query, next) : next(err);
    });
};

ArticleVersionServiceAuth.update = function updateAuth(data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.update(data, next) : next(err);
    });
};

ArticleVersionServiceAuth.remove = function removeAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.remove(pkValue, next) : next(err);
    });
};

ArticleVersionServiceAuth.findById = function findByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.VIEW, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.findById(pkValue, next) : next(err);
    });
};

ArticleVersionServiceAuth.deleteById = function deleteByIdAuth(pkValue, pv, next) {
    pv.hasPermission(PermissionActions.DELETE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.deleteById(pkValue, next) : next(err);
    });
};

ArticleVersionServiceAuth.updateById = function updateByIdAuth(pkValue, data, pv, next) {
    pv.hasPermission(PermissionActions.UPDATE, pkValue, function (err, perm) {
        (perm && perm.isAuthorized === true) ? ArticleVersionBaseService.updateById(pkValue, data, next) : next(err);
    });
};

ArticleVersionServiceAuth.find = function findAuth(query, roles, next) {
    ArticleVersionBaseService.getDataSource().queryHook.authorizedFind(roles, modelName, query, next);
};
ArticleVersionServiceAuth.count = function countAuth(where, roles, next) {
    ArticleVersionBaseService.getDataSource().queryHook.authorizedCount(roles, modelName, where, next);
};

ArticleVersionServiceAuth.findOne = function findOneAuth(query, roles, next) {
    this.find(query, roles, function (err, models) {
        next(err, (!err && models && models.length > 0) && models[0]);
    });
};



//finders implementation


module.exports = ArticleVersionServiceAuth;